openapi: 3.2.0
info:
  title: katana-api-gateway Factory Controller API
  version: 0.0.1
  description: public api
  contact: {}
servers:
- url: https://api.katanamrp.com/v1
tags:
- name: Factory Controller
paths:
  /factory:
    get:
      x-controller-name: FactoryController
      x-operation-name: getFactory
      tags:
      - Factory Controller
      responses:
        '200':
          description: Return value of FactoryController.getFactory
      operationId: FactoryController.getFactory
      summary: Factory controller get factory
      x-summary-source: derived
