openapi: 3.2.0
info:
  title: katana-api-gateway Users Controller API
  version: 0.0.1
  description: public api
  contact: {}
servers:
- url: https://api.katanamrp.com/v1
tags:
- name: Users Controller
paths:
  /user_info:
    get:
      x-controller-name: UsersController
      x-operation-name: getUserInfo
      tags:
      - Users Controller
      responses:
        '200':
          description: Return value of UsersController.getUserInfo
      operationId: UsersController.getUserInfo
      summary: Users controller get user info
      x-summary-source: derived
  /users:
    get:
      x-controller-name: UsersController
      x-operation-name: getAllUsers
      tags:
      - Users Controller
      responses:
        '200':
          description: Return value of UsersController.getAllUsers
      operationId: UsersController.getAllUsers
      parameters:
      - name: pagination
        in: query
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      summary: Users controller get all users
      x-summary-source: derived
