openapi: 3.0.0
info:
  title: katana-api-gateway AdditionalCostController FactoryController API
  version: 0.0.1
  description: public api
  contact: {}
servers:
- url: https://api.katanamrp.com/v1
tags:
- name: FactoryController
paths:
  /factory:
    get:
      x-controller-name: FactoryController
      x-operation-name: getFactory
      tags:
      - FactoryController
      responses:
        '200':
          description: Return value of FactoryController.getFactory
      operationId: FactoryController.getFactory
